/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "uart.h"
#include "lcd.h"
#include "accel.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {

	char str[32];
	AccelData_t accel;
	LcdInit();
	AccelInit();
	UartInit(9600);
	while(AccelWaitForChange()){
		AccelRead(&accel);
		sprintf(str, "%d, %d",accel.x, accel.y);
		LcdPuts(LCD_LINE1, str);
		UartPuts(str);
		UartPuts("\r\n");

		sprintf(str,"ACCEL %d ",accel.z);
		LcdPuts(LCD_LINE2, str);
		UartPuts(str);
		UartPuts("\r\n");
		DelayMs(1000);



	}


}




